import Bonjour from "bonjour-service";
import type { Service } from "bonjour-service";
import type { Peer } from "./types.js";

// mDNS service type used to advertise and discover collab sessions on the LAN (REQ-01)
export const COLLAB_SERVICE_TYPE = "_bart-collab._tcp";

// Current wire protocol version — checked on join to reject incompatible peers
export const COLLAB_PROTOCOL_VERSION = 1;

// Fields embedded in the mDNS TXT record (REQ-01, REQ-02, REQ-03)
export interface CollabTxtRecord {
  code: string;    // short join code generated by the host
  peer: string;    // host peer ID (UUID)
  gitName: string; // git user.name of the host (REQ-08)
  version: string; // stringified COLLAB_PROTOCOL_VERSION
}

// A discovered peer on the LAN, before a TCP connection is established
export interface DiscoveredHost {
  host: string;
  port: number;
  txt: CollabTxtRecord;
}

// Callbacks supplied to the advertise/browse implementations (filled in by B1)
export interface DiscoveryAdvertiser {
  stop(): void;
}

export interface DiscoveryBrowser {
  /** Resolves with the first host whose join code matches, or rejects on timeout */
  find(code: string, timeoutMs?: number): Promise<DiscoveredHost>;
  stop(): void;
}

// Factory signatures implemented in discovery.ts by workstream B (task B1)
export type CreateAdvertiser = (peer: Peer, code: string, port: number) => DiscoveryAdvertiser;
export type CreateBrowser = () => DiscoveryBrowser;

// ── bonjour-service type is e.g. "bart-collab"; protocol is "tcp" ─────────────
const BONJOUR_TYPE = "bart-collab";
const BONJOUR_PROTOCOL = "tcp" as const;
const DEFAULT_DISCOVER_TIMEOUT_MS = 10_000;

/**
 * Advertise a bart-collab session on the LAN via mDNS (REQ-02).
 * Embeds the join code and peer metadata in the TXT record so joiners can filter.
 */
export const createAdvertiser: CreateAdvertiser = (
  peer: Peer,
  code: string,
  port: number
): DiscoveryAdvertiser => {
  const bjr = new Bonjour();
  const txt: CollabTxtRecord = {
    code,
    peer: peer.id,
    gitName: peer.gitName,
    version: String(COLLAB_PROTOCOL_VERSION),
  };

  bjr.publish({
    name: `bart-collab-${peer.id}`,
    type: BONJOUR_TYPE,
    protocol: BONJOUR_PROTOCOL,
    port,
    txt: txt as unknown as Record<string, string>,
  });

  return {
    stop(): void {
      bjr.unpublishAll(() => bjr.destroy());
    },
  };
};

/**
 * Browse for bart-collab hosts on the LAN (REQ-01, REQ-03).
 * Call `.find(code)` to wait for a host with a matching join code.
 */
export const createBrowser: CreateBrowser = (): DiscoveryBrowser => {
  const bjr = new Bonjour();

  return {
    find(code: string, timeoutMs = DEFAULT_DISCOVER_TIMEOUT_MS): Promise<DiscoveredHost> {
      return new Promise((resolve, reject) => {
        let settled = false;

        const browser = bjr.find(
          { type: BONJOUR_TYPE, protocol: BONJOUR_PROTOCOL },
          (service: Service) => {
            if (settled) return;

            const txt = service.txt as Record<string, string> | undefined;
            if (!txt || txt.code !== code) return;

            // Reject peers running an incompatible protocol version
            const version = parseInt(txt.version ?? "0", 10);
            if (version !== COLLAB_PROTOCOL_VERSION) {
              reject(
                new Error(
                  `Incompatible protocol version ${version} (expected ${COLLAB_PROTOCOL_VERSION})`
                )
              );
              settled = true;
              browser.stop();
              return;
            }

            settled = true;
            browser.stop();

            // Prefer an IPv4 address when multiple addresses are advertised
            const host =
              service.addresses?.find((a) => !a.includes(":")) ??
              service.host;

            resolve({
              host,
              port: service.port,
              txt: txt as unknown as CollabTxtRecord,
            });
          }
        );

        const timer = setTimeout(() => {
          if (settled) return;
          settled = true;
          browser.stop();
          reject(
            new Error(
              `No bart-collab host found with code "${code}" within ${timeoutMs}ms`
            )
          );
        }, timeoutMs);

        if (typeof timer.unref === "function") timer.unref();
      });
    },

    stop(): void {
      bjr.destroy();
    },
  };
};
